### ISSUE TITLE
Player sticks to walls mid jump

### ISSUE THREAD

**Issue by Nuadhain** [Creative-Corner-Studios/Pulp-Legends#6]

**Comment by Josh9309** [comment]
I fixed the bug where if player was providing input against an obstacle
in the air it would cause the player to not fall down the wall. but
instead remain in that position. I do not know exactly what is causing
this bug but i am guessing it has to do with back-end unity stuff. The
way i was able to fix it was by creating a bool called air-control that
gives the player the ability to maneuver in the air. If the player
collided with anything in the air, they would lose their ability to
maneuver in the air until they are no longer colliding with it.
